services:
  uploader:
    image: ghcr.io/magnusakselvoll/firefly-iii-custom-uploader:latest
    ports:
      - "8080:8080"
    environment:
      FireflyIiiCustomUploader__FireflyIiiUrl: "http://firefly:8080"
      FireflyIiiCustomUploader__FireflyIiiToken: "your-personal-access-token"
      # FireflyIiiCustomUploader__WebListenUrl: "http://0.0.0.0:8080"
      # FireflyIiiCustomUploader__RunTagPrefix: "ffcu-upload"
